// PRUNE: KEEP_ALL  (This file intentionally contains multiple stories for documentation & visual regression.)
// Expanded Button stories demonstrating variants, sizes, states, and behaviors.
import type { Meta, StoryObj } from "@storybook/react";
import { Button } from "./Button";
import ParityBlock, { toNunjucksMacro } from "../../storybook/ParityBlock";
// Load the canonical static HTML snippet generated by scripts/generate-static-html-examples.ts
// Vite allows importing raw file contents with the ?raw suffix
// The path is relative to this file: src/components/Button -> ../../../docs/static-html
import buttonStaticHtml from "../../../docs/static-html/Button.html?raw";

const meta: Meta<typeof Button> = {
	title: "NHS/Components/Button",
	component: Button,
	parameters: {
		layout: "centered",
		docs: {
			description: {
				component: `
The NHS Button component provides excellent accessibility support with native HTML elements. It follows NHS design guidelines and includes:

## Features

- **Full keyboard navigation**: Tab, Enter, and Space key support
- **Screen reader compatibility**: Proper ARIA labels and descriptions
- **Focus management**: Smart focus handling and focus-visible support
- **Press state management**: Visual and behavioral press states
- **Hover interactions**: Enhanced hover states with animations
- **Touch support**: Optimized for touch interactions

## Usage

\`\`\`tsx
import { Button } from '@nhs-fdp/design-system';

// Basic usage
<Button variant="primary">Continue</Button>

// With all props
<Button 
  variant="secondary" 
  size="large"
  fullWidth
  disabled
  onClick={() => console.log('Clicked!')}
>
  Click me
</Button>
\`\`\`

## Background Guidelines

### Light Backgrounds
- **Primary**: Green button for main actions
- **Secondary**: Blue outlined button for secondary actions  
- **Login**: Blue button for authentication

### Dark Backgrounds (NHS Blue, etc.)
- **Reverse**: White button that works on dark backgrounds

### Special Cases
- **Warning**: Red button for destructive actions

## Native Accessibility

This component uses native HTML elements to provide:
- Automatic ARIA attributes
- Keyboard event handling
- Focus management
- Press state detection
- Touch gesture support
- Screen reader announcements
        `,
			},
		},
	},
	argTypes: {
		variant: {
			control: "select",
			options: [
				"primary",
				"secondary",
				"reverse",
				"warning",
				"login",
				"metric",
				"metric-blue",
				"metric-green",
				"metric-warning",
			],
		},
		size: {
			control: "select",
			options: ["small", "default", "large"],
		},
		fullWidth: {
			control: "boolean",
		},
		children: {
			control: "text",
		},
	},
};

export default meta;
type Story = StoryObj<typeof Button>;

// Variant stories
export const Primary: Story = {
	args: { variant: "primary", children: "Primary action" },
};

export const PrimaryDisabled: Story = {
	args: {
		variant: "primary",
		children: "Primary disabled",
		disabled: true,
	} as any,
};

export const Secondary: Story = {
	args: { variant: "secondary", children: "Secondary action" },
};

export const SecondaryDisabled: Story = {
	args: {
		variant: "secondary",
		children: "Secondary disabled",
		disabled: true,
	} as any,
};

export const Reverse: Story = {
	args: { variant: "reverse", children: "Reverse on dark BG" },
	globals: {
        backgrounds: {
            value: "dark"
        }
    },
};

export const Warning: Story = {
	args: { variant: "warning", children: "Destructive action" },
};

export const Login: Story = {
	args: { variant: "login", children: "Login" },
};

export const Metric: Story = {
	args: { variant: "metric", children: "Metric action" },
	parameters: {
		docs: {
			description: {
				story:
					"Metric-inspired button: card-like surface with left accent bar, blending MetricCard aesthetics with NHS Button semantics.",
			},
		},
	},
};

	export const MetricBlue: Story = {
		args: { variant: "metric-blue", children: "Metric blue" },
	};

	export const MetricGreen: Story = {
		args: { variant: "metric-green", children: "Metric green" },
	};

	export const MetricWarning: Story = {
		args: { variant: "metric-warning", children: "Metric warning" },
	};



// Layout & width
export const FullWidth: Story = {
	args: { variant: "primary", fullWidth: true, children: "Full width button" },
	parameters: { layout: "padded" },
};

// Link rendering
export const AsLink: Story = {
	args: { variant: "secondary", href: "#next", children: "Anchor link button" },
};

// Double‑click prevention demonstration
export const PreventDoubleClick: Story = {
	args: {
		variant: "primary",
		preventDoubleClick: true,
		children: "Submit (1s lockout)",
	},
	parameters: {
		docs: {
			description: {
				story:
					"Demonstrates preventDoubleClick — clicking rapidly will only trigger first activation for 1 second.",
			},
		},
	},
};

// Composite gallery (for visual scan of main variants) – hidden from docs table.
export const Gallery: Story = {
	parameters: { docs: { disable: true } },
	render: () => (
		<div
			style={{
				display: "flex",
				flexWrap: "wrap",
				gap: "12px",
				alignItems: "flex-start",
			}}
		>
			<Button variant="primary">Primary</Button>
			<Button variant="secondary">Secondary</Button>
			<Button variant="reverse">Reverse</Button>
			<Button variant="warning">Warning</Button>
			<Button variant="login">Login</Button>
			<Button variant="metric">Metric</Button>
					<Button variant="metric-blue">Metric blue</Button>
					<Button variant="metric-green">Metric green</Button>
					<Button variant="metric-warning">Metric warning</Button>
			<Button variant="secondary" disabled>
				Disabled
			</Button>
			<Button variant="primary" preventDoubleClick>
				Prevent dbl‑click
			</Button>
		</div>
	),
};

// Parity panel: React render, Nunjucks macro (code), Static HTML snippet (rendered)
export const Parity: Story = {
	name: "Parity: React | Nunjucks | Static HTML",
	args: { variant: "primary", children: "Continue" },
	parameters: {
		layout: "padded",
		docs: {
			description: {
				story:
					"Side-by-side view: React live render, Nunjucks macro invocation (code), and the canonical Static HTML snippet (generated).",
			},
		},
	},
	render: (args) => {
		const props: Record<string, unknown> = {
			text: typeof args.children === "string" ? args.children : "Continue",
			variant: (args as any).variant,
		};
		if ((args as any).href) (props as any).href = (args as any).href;
		if ((args as any).fullWidth) (props as any).fullWidth = true;
		if ((args as any).disabled) (props as any).disabled = true;
		if ((args as any).size && (args as any).size !== "default")
			(props as any).size = (args as any).size;

		return (
			<ParityBlock
				macroCode={toNunjucksMacro("button", props)}
				staticHtml={buttonStaticHtml}
			>
				<Button {...args} />
			</ParityBlock>
		);
	},
};
